FRAGMENT:
  tasks:
  dt: 0.1
  maxTestTime: 30
  skipExist: True

SERIAL:
  tasks:
  dt: 0.05
  maxTestTime: 200
  skipExist: True

REPLAY:
  tasks:
    - mixed_952_32_1
  visualize: True
  skipExist: False
