replay:
  tasks:
    - intersection_12_61_0
    - intersection_12_61_1
    - intersection_12_61_2
  visualize: True

fragment:
  tasks: 
    - test1
    - test2
  dt: 0.1
  maxTestTime: 30

serial:
  tasks:
    - Cyz_TJST_1.json
    - Cyz_TJST_2.json
  dt: 0.05
  maxTestTime: 200
  